---

- name: Ensure that letsencrypt home is exists
  file: state=directory path="{{letsencrypt_home}}"

- name: Run docker-letsencrypt and setup sertificates
  docker:
    command: "{{letsencrypt_command}}"
    env: "{{letsencrypt_env}}"
    image: "{{letsencrypt_image}}"
    name: letsencrypt
    ports: ["80:80", "443:443"]
    volumes: ["{{letsencrypt_home}}:/etc/letsencrypt"]
