---

- name: Ensure that letsencrypt home is exists
  file: state=directory path="{{letsencrypt_home}}"

- name: Run docker-letsencrypt and setup sertificates
  docker:
    command: "{{letsencrypt_command}}"
    image: "{{letsencrypt_image}}"
    name: letsencrypt
    ports: ["80:80", "443:443"]
    volumes: ["{{letsencrypt_home}}:/etc/letsencrypt"]
    env:
      LETSENCRYPT_EMAIL: "{{letsencrypt_email}}"
      LETSENCRYPT_DOMAIN1: "{{letsencrypt_domain}}"
